name: "VecturaKit CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-15
    env:
      DEVELOPER_DIR: "/Applications/Xcode_16.1.app/Contents/Developer"
    steps:
      - uses: actions/checkout@v4
      - name: Build and Test
        run: swift test