name: Build and Test VecturaKit and CLI

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: macos-latest
    strategy:
      matrix:
        target: [ "VecturaKit", "vectura-cli" ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app
      - name: Build target ${{ matrix.target }}
        run: swift build --product "${{ matrix.target }}"
      - name: Run tests
        run: swift test
